apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html
        image: dockerhub_username/html-app:latest
        ports:
        - containerPort: 80
